### ISSUE TITLE
ASR

### ISSUE THREAD

**Issue by DeastinY** [iMicknl/LoctekMotion_IoT#24]
I've been using the ESPHome variant for a few days and today set up an automation to press M1 / M2 every 30 minutes. After some time it failed and the display showed "ASR".  
Couldn't control anything with the ESP anymore and needed to attach the panel and move the desk all the way down to reset it.
Anyone already had similar issues? Something to expect to happen more often?

**Comment by DeastinY** [comment]
I've encountered the issue so often that I stopped using it altogether :/  
In the short time I tried to look into it I couldn't really get any information together, so I just stopped.
Willing to help if anyone wants to look into this though, if time permits.

**Comment by xkisu** [comment]
I'm getting this frequently as well too, I've tried adjusting the esp home config a bit to cover what I thought where some edge cases with the cover but it hasn't helped.

Desk: PrimeCables PLUS+
Control Panel: Loctek HS01B-1

It seems to get stuck in the ASR/Reset mode any time I leave it and don't move the desk for several hours. 

On a side note, I added a button component to reset it (but I've had intermittent success with wether it works or not, sometimes you hear the relay clicking to move the desk down but it doesn't actually move):
```yaml
button:
  ...
  - platform: template
    name: "Reset Desk"
    on_press:
      - while:
          condition:
            sensor.in_range:
              id: desk_height
              # When the desk is in ASR/Reset mode is appears to return an invalid height of 50cm.
              #
              # When this happens, the down button needs to be held until the desk lowers all the way
              # and the height resets to the correct minimum height.
              below: ${min_height}
          then:
            - logger.log: "Executing down command"
            - button.press: button_down
            - delay: 10ms
```
