### ISSUE TITLE
Support request for model HCB213A-1

### ISSUE THREAD

**Issue by lboue** [iMicknl/LoctekMotion_IoT#37]
Hello,

The HCB213A-1 model does not appear on the supported models page.
Here is a picture below:

![HCB213A-1](https://user-images.githubusercontent.com/938089/193634645-13c83046-1505-4829-81c2-4e99ac7d58ee.jpg)

Regards

**Comment by horriblenoises** [comment]
I just got an [EN1B desk frame off amazon](https://www.amazon.com/dp/B07GWCSXJ8) (in the US) with this model controller and connected a D1 mini to it with the ESPhome instructions and the e5b yaml file. It required minimal modifications (min/max height adjustment & adding preset 4) but I'm very happy to say it seems to work really well. Cover up/down travel the desk to min/max, the presets all work, and the height readout is correctly displayed in Home Assistant.
<img width="336" alt="Screen Shot 2022-10-21 at 12 24 23 AM" src="https://user-images.githubusercontent.com/66970539/197111677-218669d4-e510-4aae-a456-dfd68753fd64.png">

**Comment by renjithstalin** [comment]
@horriblenoises Can you please share your preset 4 entry? also, does down button work for you? Thanks in advance

**Comment by horriblenoises** [comment]
@renjithstalin  

Sorry. I got distracted from this project for a bit. Never added the problems I'd found after posting that. It seems like the up/down buttons don't work after a timeout occurs. Pin20 doesn't seem to wake it either. So I changed up/down to internal in the esphome yaml. My D1 mini also reboot a lot after a command is finished. I have to investigate if it's something I've done or something that isn't compatible.

This aside, it does work as well as I need it to. The preset buttons are not effected by the timeout issue so I set P1 to min, P4 to max, and if I need granularity beyond that, I can always add an automation to Home Assistant or the ESP to call for specified heights (send button press P4; if height = height requested -1, send button press P4 again to stop).

```
  - platform: uart
    name: "Preset 1"
    id: ${device_name}_preset1
    icon: mdi:numeric-1-box
    data: [0x9b, 0x06, 0x02, 0x04, 0x00, 0xac, 0xa3, 0x9d]
    uart_id: desk_uart

  - platform: uart
    name: "Preset 2"
    id: ${device_name}_preset2
    icon: mdi:numeric-2-box
    data: [0x9b, 0x06, 0x02, 0x08, 0x00, 0xac, 0xa6, 0x9d]
    uart_id: desk_uart

  - platform: uart
    name: "Preset 3"
    id: ${device_name}_preset3
    icon: mdi:numeric-3-box
    data: [0x9b, 0x06, 0x02, 0x10, 0x00, 0xac, 0xac, 0x9d]
    uart_id: desk_uart

  - platform: uart
    name: "Preset 4"
    id: ${device_name}_preset4
    icon: mdi:numeric-4-box
    data: [0x9b, 0x06, 0x02, 0x00, 0x01, 0xac, 0x60, 0x9d]
    uart_id: desk_uart

  - platform: uart
    name: "Up"
    id: ${device_name}_up
    icon: mdi:arrow-up-bold
    data: [0x9b, 0x06, 0x02, 0x01, 0x00, 0xfc, 0xa0, 0x9d]
    uart_id: desk_uart
    internal: true

  - platform: uart
    name: "Down"
    id: ${device_name}_down
    icon: mdi:arrow-down-bold
    data: [0x9b, 0x06, 0x02, 0x02, 0x00, 0x0c, 0xa0, 0x9d]
    uart_id: desk_uart
    internal: true
```

**Comment by renjithstalin** [comment]
Many thanks for the response. I have managed to get Preset 4 working. But my down button still doesn't work. I'm going to try this with esp32 and see if it works. And yes, my wemos d1 mini reboots too :(
Thanks again.

**Comment by sebPomme** [comment]
> It seems like the up/down buttons don't work after a timeout occurs.

I read somewhere on another model that UP/DOWN work only if the panel light are turn on before :thinking: so the trick was to send an impulsion to a pin that are link to the screen before doing an action .  
I c'ant remember where.

May we can apply the same pattern.

**Comment by lourdrivera123** [comment]
> Many thanks for the response. I have managed to get Preset 4 working. But my down button still doesn't work. I'm going to try this with esp32 and see if it works. And yes, my wemos d1 mini reboots too :( Thanks again.

Were you able to test it on esp32? 
We have the same model of control panel, but I don't know how to map it correctly with my RJ45 and ESP32 Devkit V1.

**Comment by ThomDietrich** [comment]
Hey guys, thanks for confirming that it works for the HCB213A-1. I bought the desk "Sanodesk EC4 "EC4B-EU and it came with the controller box HCB2**2**3A-1. I expect it to be identical, except for the two-motor-drive. I'll try with the e5b yaml and an esp32 the next couple of days.

For who might find it useful, here are some pictures of the controller:

![telegram-cloud-photo-size-2-5262495425334725914-y](https://github.com/iMicknl/LoctekMotion_IoT/assets/2870104/8bfb42ca-275c-489c-86ad-36976bf22813)
![telegram-cloud-photo-size-2-5262495425334725915-y](https://github.com/iMicknl/LoctekMotion_IoT/assets/2870104/8a35b1d2-cd94-4dfc-b4d4-56acc9b3929e)
![telegram-cloud-photo-size-2-5262495425334725916-y](https://github.com/iMicknl/LoctekMotion_IoT/assets/2870104/ce7d7c47-102e-433c-bc46-7ab436f833ff)

**Comment by ThomDietrich** [comment]
Couldn't wait 😄 

I've quickly thrown together an RJ45 to ESP32 cable and flashed the firmware. I can confirm that everything is working. This includes the up and down commands - no wake-up or PIN20 needed (both of those seem to have no effect on my specific device).

The only bug I found is that "Desk Height" stays unknown after the ESP boots up. This can be resolved via a wake-up (display or programmatically) and isn't a bigger issue for my use cases. Still, I found another workaround for waking up the device: If a preset button is not programmed to a specific height, it will wake up the display but won't move the desk.

**Comment by iMicknl** [comment]
@ThomDietrich would you be willing to test https://github.com/iMicknl/LoctekMotion_IoT/issues/67? Hopefully this will also solve your issues.

**Comment by Zagur** [comment]
> Couldn't wait 😄
> 
> I've quickly thrown together an RJ45 to ESP32 cable and flashed the firmware. I can confirm that everything is working. 🎉 This includes the up and down commands - no wake-up or PIN20 needed (both of those seem to have no effect on my specific device).
> 
> The only bug I found is that "Desk Height" stays unknown after the ESP boots up. This can be resolved via a wake-up (display or programmatically) and isn't a bigger issue for my use cases. Still, I found another workaround for waking up the device: If a preset button is not programmed to a specific height, it will wake up the display but won't move the desk.

I currently have an HCB213A-1 and I was testing with the configuration for e5b with what you have mentioned. I am using an ESP328266 Mod, what scheme should I follow to connect the cables correctly?

**Comment by ThomDietrich** [comment]
Hey @Zagur, you should find everything you need in https://github.com/iMicknl/LoctekMotion_IoT/issues/67

**Comment by Zagur** [comment]
First of all I want to thank everyone for this incredible project.

I have been reading several issues and have configured my ESP32 2866 to control the HCB213A-1 controller. Everything seems to be working correctly except for one thing I've seen in Home Assistant.

When I try to set the height to 90cm it always adds between 2 and 2.7cm extra. I use the mushroom-number-card to show the height but it doesn't work very well. A value is always set below or above what is indicated.

Doing some tests I get some ideas/doubts:

- Would it be possible that the switch_up and switch_down, instead of going up to the maximum or minimum, did it in 5 at a time or 10 at a time? (maybe put a parameter to configure this).

Regards!

**Comment by pabsi** [comment]
Hello,
I know it's a very old issue, but in case it helps anyone, specifically the OP:
I was able to make my *Flexispot EF1* work very nicely following instructions on https://github.com/iMicknl/LoctekMotion_IoT/issues/67 (thank you so much @iMicknl !!).
There's some minor issues (nothing major in my opinion) but man, I even have the alarm working! Something I couldn't even set up with the physical keys lol...

Attaching some photos of the final connections, pinouts, etc. I used an ESP32 WROOM board.
My desk control unit is exactly a *HCB213A-1*.

<img width="1080" height="1673" alt="Image" src="https://github.com/user-attachments/assets/91966482-1b47-4d4b-83e3-da68b557a479" />
<img width="1080" height="1920" alt="Image" src="https://github.com/user-attachments/assets/380781a0-bbe5-4879-87b2-0102ba9d3a27" />
<img width="1080" height="1920" alt="Image" src="https://github.com/user-attachments/assets/74deb091-eb93-4d24-a337-cf6cc26e8b39" />
<img width="1080" height="1920" alt="Image" src="https://github.com/user-attachments/assets/c27460e0-7868-43bf-874d-bd3a938bbf75" />

My working YAML code for the ESPhome:
```
substitutions:
  device_name: Flexispot EF1
  name: flexispot-ef1
  min_height: "71.0" # cm
  max_height: "121.0" # cm
  ap_fallback_password: "MnANX95MWad1"
  tx_pin: GPIO17 # TXD 2
  rx_pin: GPIO16 # RXD 2
  screen_pin: GPIO23
  encryption_key: "GxluDMysqVoAZNNtX/oHNmj5tso3hmsw1gUfMn/lDXA="

external_components:
  source: github://iMicknl/LoctekMotion_IoT@v2
  components: [ loctekmotion_desk_height ]

esp32:
  board: esp32dev
  framework:
    type: arduino

esphome:
  name: ${name}
  friendly_name: ${device_name}
  comment: Used to control your ${device_name} standing desk via Home Assistant.

  # Wake Desk by sending the "M" command
  # This will pull the current height after boot
  on_boot:
    priority: -10
    then:
      - button.press: button_m


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ${encryption_key}

ota:
  - platform: esphome
    password: "70635c2c8c073cacf23da9d108ae2f32"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  - id: desk_uart
    baud_rate: 9600
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: Uptime

  - platform: loctekmotion_desk_height
    id: "desk_height"
    name: Desk Height
    on_value_range:
    - below: ${min_height}
      then:
        - switch.turn_off: switch_down
    - above: ${max_height}
      then:
        - switch.turn_off: switch_up
    on_value:
      then:
        - cover.template.publish:
            id: desk_cover
            position: !lambda |-
                // The sensor outputs values from min_height (cm) to max_height (cm)
                // We need to translate this to 0 - 1 scale.
                float position = (float(x) - float(${min_height})) / (float(${max_height}) - float(${min_height}));
                return position;
        - component.update: set_desk_height

switch:
  - platform: gpio
    name: "Virtual Screen" # PIN20
    pin:
      number: ${screen_pin}
      mode: OUTPUT
    restore_mode: ALWAYS_ON
    entity_category: "config"
    internal: true

  - platform: uart
    name: "Up"
    id: switch_up
    icon: mdi:arrow-up-bold
    data: [0x9b, 0x06, 0x02, 0x01, 0x00, 0xfc, 0xa0, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    internal: true

  - platform: uart
    name: "Down"
    id: switch_down
    icon: mdi:arrow-down-bold
    data: [0x9b, 0x06, 0x02, 0x02, 0x00, 0x0c, 0xa0, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    internal: true

  - platform: uart
    name: "Alarm off"
    id: switch_alarm
    icon: mdi:alarm
    data: [0x9b, 0x06, 0x02, 0x40, 0x00, 0xAC, 0x90, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    on_turn_on:
      - delay: 3000ms
      - switch.turn_off: switch_alarm
    entity_category: "config"

  - platform: uart
    name: "Child Lock"
    id: switch_child_lock
    icon: mdi:account-lock
    data: [0x9b, 0x06, 0x02, 0x20, 0x00, 0xac, 0xb8, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    on_turn_on:
      - delay: 5000ms
      - switch.turn_off: switch_child_lock
    entity_category: "config"

button:
  - platform: template
    name: "Preset 1"
    icon: mdi:chair-rolling
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x04, 0x00, 0xac, 0xa3, 0x9d]

  - platform: template
    name: "Preset 2"
    icon: mdi:human-handsup
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x08, 0x00, 0xac, 0xa6, 0x9d]

  - platform: template
    name: "Preset 3" # Preset 4 on some control panels
    icon: mdi:numeric-3-box
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x10, 0x00, 0xac, 0xac, 0x9d]

  - platform: template
    name: "Preset 4" # Preset 3 on some control panels
    icon: mdi:numeric-4-box
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x00, 0x01, 0xac, 0x60, 0x9d]

  - platform: template
    name: "Memory"
    id: button_m
    icon: mdi:alpha-m-box
    entity_category: "config"
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x20, 0x00, 0xac, 0xb8, 0x9d]

  - platform: template
    name: "Wake Screen"
    id: button_wake_screen
    icon: mdi:gesture-tap-button
    entity_category: "config"
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x00, 0x00, 0x6c, 0xa1, 0x9d]

  - platform: template
    name: "Alarm"
    id: button_alarm
    icon: mdi:alarm
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x40, 0x00, 0xAC, 0x90, 0x9d]

  - platform: restart
    name: "Restart"
    entity_category: "config"

cover:
  - platform: template
    id: "desk_cover"
    icon: phu:desk-stand-alt
    name: "Desk"
    device_class: blind # makes it easier to integrate with Google/Alexa
    has_position: true
    position_action:
      - if:
          condition:
            - lambda: !lambda |-
                return pos > id(desk_cover).position;
          then:
            - cover.open: desk_cover
            - wait_until:
                lambda: |-
                  return id(desk_cover).position  >= pos;
            - cover.stop: desk_cover
          else:
            - cover.close: desk_cover
            - wait_until:
                lambda: |-
                  return id(desk_cover).position <= pos;
            - cover.stop: desk_cover
    stop_action:
      - switch.turn_off: switch_up
      - switch.turn_off: switch_down
    open_action:
      - switch.turn_off: switch_down
      - switch.turn_on: switch_up
    close_action:
      - switch.turn_off: switch_up
      - switch.turn_on: switch_down
    optimistic: false

number:
  - platform: template
    name: "Desk Height"
    id: set_desk_height
    min_value: ${min_height}
    max_value: ${max_height}
    icon: "mdi:counter"
    unit_of_measurement: "cm"
    device_class: "distance"
    step: 0.1
    lambda: !lambda |-
      return id(desk_height).state;
    set_action:
      - if:
          condition:
            - lambda: !lambda |-
                return x > id(desk_height).state;
          then:
            - cover.open: desk_cover
            - wait_until:
                lambda: |-
                  return id(desk_height).state  >= x;
            - cover.stop: desk_cover
          else:
            - cover.close: desk_cover
            - wait_until:
                lambda: |-
                  return id(desk_height).state <= x;
            - cover.stop: desk_cover
```

<img width="1044" height="1103" alt="Image" src="https://github.com/user-attachments/assets/f44d5152-c5c9-4a66-8aaf-7d7e12755c18" />

Issues I noticed (super minors for me, for now):
* Presets 3 and 4 are inverted (3 is 4 and viceversa)
* The "Wake screen" button doesn't actually wake the screen. Unsure if it has some sort of hidden purpose.
* When selecting a preset, the "stop" button does not stop it. Other preset button stops it from moving immediately.
* The child lock has some weirdness, though this is probably the board. Like it says it locks, but pressing 1 button works, other is locked, and after a few presses all unlock....dunno, strange stuff

Anyway, can't thank you enough!! Will definitely make a donation 🥇
