### ISSUE TITLE
Update height when controlling through original keypad

### ISSUE THREAD

**Issue by lilaelephant** [iMicknl/LoctekMotion_IoT#71]
Hi, thanks so much for this repo! I have followed the instructions over a year ago using the Flexispot E7 and it works quite well! I'm using the following keypad:

<img width="584" alt="image" src="https://github.com/iMicknl/LoctekMotion_IoT/assets/84687112/86e59726-e1aa-4b18-9ca7-cf0ff60d2193">

Luckily my adapter provides two RJ45 ports, so I still use the original keypad while also being able to control it using Home Assistant.

### My problem

I'm trying to create push notifications and collect statistics, so that I can better motivate myself to regularly stand. But when I use the keypad, the new height doesn't get detected. It is displayed on the keypad itself but the only way to also get it into Home Assistant is by sending the the "M" command or rebooting the device. This is quite annoying because it always lights up the display (I sleep in the same room).

Is there any way to properly read out the current height without having to send the "M" command or control the device using Home Assistant? I would love to keep using the keypad but get the benefit of collecting statistics and to set up push notifications to remind myself to stand (for example when I'm currently in a work meeting).

**Comment by iMicknl** [comment]
Have you tried the V2 pinout and YAML? See the pinned issue.

**Comment by jacobbjo** [comment]
Hi, I'm having the same issue where the height is not updated when using the original keypad or when pushing the preset buttons in home assistant.

**Desk model:** Flexispot E7
**Control panel:** HS13B-1
**Control box:** CB38M2J(IB)-1

**Using this pinout:**
|RJ45 pin | Name | ESP32|
|--------|--------|--------|
|8 | +5V (VDD) | VIN|
|7 | GND | GND|
|6 | TX | TX2 (GPIO17)|
|5 | RX | RX2 (GPIO16)|
|4 | PIN 20 | D23 (GPIO23)|
|3 | (unknown) |  |
|2 | SWIM |  |
|1 | RES |  |

I uncommented the ESP_LOGD lines in the "desk_height_sensor.h" to try to look at what is received. 

When doing nothing, I can see that these six bytes are received over and over again:
0000009b
00000004
00000011
0000007c
000000c3
0000009d

When changing the table height with the up/down cover arrows in home assistant I can see that new height information is received continuously, all good.

When pressing the preset buttons in home assistant or when operating the original keypad (preset or up/down) I just see the above mentioned bytes over and over. The display on the original keypad is however updated continuously as the table moves. 

It is just as if the two RJ45 jacks on the controller does not get the same data.

Anyone else with the same control panel + control box that has this working properly?

I'm thinking of creating a cable that piggybacks on the transmitting line to the original control panel to see if I can see some other data.

**Comment by voydz** [comment]
Hey there.

I am experiencing the same issue. No height update when using the keypad and presets (through HA).

I got the exact same setup and environment as @jacobbjo 

best regards

**Comment by voydz** [comment]
Hey folks, here are some observations.

It is not entirely true, that the height is not updated at all. I am experience a single update tick after i.e. calling a preset. Afterwards there are no more updates. 
Unfortunately I do not have the time to look into this right now, but I am leaving it here, maybe someone got an idea or at least is pushed in the right direction with this information.

![Bildschirmfoto 2024-02-19 um 11 57 35](https://github.com/iMicknl/LoctekMotion_IoT/assets/373533/5b2d7bec-6876-400b-92a9-b039a02cdd88)

**Comment by SasStu** [comment]
I have the same setup and same behavior. Everything works fine, except updating the desk height which will only update immediately after using software buttons to change the height.

**Comment by voydz** [comment]
Also, I noticed something that might (?) be relevant to this issue.

I read several times, that the control panel is protected against accidental touches. So you have to touch it once to wake the screen („Wake screen“ UART command?) and afterwards you are able to control the desk. 

My desk does not have this „feature“. Accidental touches instantly move the desk. I think I will reach out to FlexiSpot and ask about that behavior.

**Comment by lufetico** [comment]
> **Desk model:** Flexispot E7
> **Control panel:** HS13B-1
> **Control box:** CB38M2J(IB)-1

I have a Flexispot **E8** with the same Control panel and Control box as you. And I have the same problem with updating the table height when changing from the physical panel. Have you managed to solve it?

**Comment by voydz** [comment]
Currently this issue ist not fixed for me.

I got in touch with FlexiSpot about the "accidental touch prevention" I talked about before. I have to revert my suggestion. 
It seems that this behavior is only implemented on other desks. As far as I understood, no E7 with the control panel and box we are talking about have that feature.

So thats out of the equation at least.

As a possible debug setup, I thought about flipping the connection of esp and control panel, before cutting cables. I thought the CP might be quite a good debug device 😅 Maybe I will have some time to investigate on this.

**Comment by ProZsolt** [comment]
Bumping this issue. If nobody figured this out so far I'm planning to dig in.

**Comment by gitviola** [comment]
I figured it out pairing with Claude code the other week. Basically, the controller is programmed in a way that it only sends the hight back to the device that initiated the command. So if you change the hight using the keypad, it will only send the hight updates back to the keypad.

It is sent through a specific wire (**in my case** the white-blue wire). So what I have done was to open up a new short RJ45 cable and tapping into the white-blue cable. To not damage the original cable going to the keypad I recommend getting a RJ45 female to female connector and basically connecting your modified cable with the original cable.

This white-blue cable you then connect to the RX pin of the esp. I put my working config below.

**Important:**
* The wire was white-blue in my set up. But it depends what type of ethernet cable you have. It could also be the green cable. So first test which one of these carries the hight info
* I'm using an esp8266, so your pins will look different in case you're using an esp32. Also, I abstracted my configs into sub-folders as I manage multiple esp devices, so you will see something like

```yaml
packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml
```

Here is my full config:
```yaml
substitutions:
  device_name: flexispot
  friendly_name: Flexispot
  device_description: "Controller for standing desk."
  min_height: "64.1" # Min height + 0.1
  max_height: "117.9" # Max height - 0.1
  standing_threshold: "88.0" # At or above = standing, below = sitting
  tx_pin: D5
  rx_pin: D6
  screen_pin: D2

external_components:
  source: github://iMicknl/LoctekMotion_IoT
  components: [ loctekmotion_desk_height ]

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  on_boot:
    priority: -200
    then:
      - if:
          condition:
            lambda: 'return id(last_known_height) > 0;'
          then:
            - sensor.template.publish:
                id: ${device_name}_desk_height
                state: !lambda 'return id(last_known_height);'

esp8266:
  board: nodemcuv2

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

# Enable logging
logger:
  # level: DEBUG
  # level: VERBOSE # Makes uart stream available in esphome logstream
  baud_rate: 0 # Disable logging over uart

# Enable Home Assistant API
api:
  # password: !secret flexispot_api_password
  encryption:
    key: !secret flexispot_api_encryption_key

ota:
  platform: esphome
  password: !secret flexispot_ota_password


############
## Custom ##
############

uart:
  - id: desk_uart
    baud_rate: 9600
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
  - id: keypad_sniff_uart
    baud_rate: 9600
    rx_pin: GPIO3   # hardware UART0 RX (NodeMCU silkscreen label "RX")

globals:
  - id: last_known_height
    type: float
    restore_value: true
    initial_value: '0.0'

sensor:
  - platform: loctekmotion_desk_height
    uart_id: keypad_sniff_uart
    id: ${device_name}_height_src_sniff
    internal: true
    on_value:
      then:
        - lambda: 'id(last_known_height) = x;'
        - sensor.template.publish:
            id: ${device_name}_desk_height
            state: !lambda 'return x;'

  - platform: loctekmotion_desk_height
    uart_id: desk_uart
    id: ${device_name}_height_src_command
    internal: true
    on_value:
      then:
        - lambda: 'id(last_known_height) = x;'
        - sensor.template.publish:
            id: ${device_name}_desk_height
            state: !lambda 'return x;'

  - platform: template
    id: ${device_name}_desk_height
    name: Desk Height
    unit_of_measurement: "cm"
    device_class: distance
    accuracy_decimals: 1
    update_interval: never
    on_value_range:
      - below: ${min_height}
        then:
          - switch.turn_off: ${device_name}_switch_down
      - above: ${max_height}
        then:
          - switch.turn_off: ${device_name}_switch_up
    on_value:
      then:
        - cover.template.publish:
            id: ${device_name}_desk_cover
            position: !lambda |-
                float position = (float(x) - float(${min_height})) / (float(${max_height}) - float(${min_height}));
                return position;
        - component.update: ${device_name}_set_desk_height
        - binary_sensor.template.publish:
            id: ${device_name}_standing
            state: !lambda 'return x >= float(${standing_threshold});'
        - text_sensor.template.publish:
            id: ${device_name}_posture
            state: !lambda 'return x >= float(${standing_threshold}) ? "standing" : "sitting";'

binary_sensor:
  - platform: template
    name: "${friendly_name} Standing"
    id: ${device_name}_standing
    icon: mdi:human-handsup

text_sensor:
  - platform: template
    name: "${friendly_name} Posture"
    id: ${device_name}_posture
    icon: mdi:seat

switch:
  # PIN20
  - platform: gpio
    name: "${friendly_name} Virtual Screen"
    pin:
      number: ${screen_pin}
      mode: OUTPUT
    restore_mode: ALWAYS_ON
    entity_category: "config" 
    internal: true

  - platform: uart
    name: "${friendly_name} Up"
    id: ${device_name}_switch_up
    icon: mdi:arrow-up-bold
    data: [0x9b, 0x06, 0x02, 0x01, 0x00, 0xfc, 0xa0, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    internal: true

  - platform: uart
    name: "${friendly_name} Down"
    id: ${device_name}_switch_down
    icon: mdi:arrow-down-bold
    data: [0x9b, 0x06, 0x02, 0x02, 0x00, 0x0c, 0xa0, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    internal: true

  - platform: uart
    name: "${friendly_name} Alarm off"
    id: switch_alarm
    icon: mdi:alarm
    data: [0x9b, 0x06, 0x02, 0x40, 0x00, 0xAC, 0x90, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    on_turn_on:
      - delay: 3000ms
      - switch.turn_off: switch_alarm
    entity_category: "config"

  - platform: uart
    name: "${friendly_name} Anti Collision"
    id: ${device_name}_switch_anti_kollision
    icon: mdi:card-remove
    data: [0x9b, 0x06, 0x02, 0x03, 0x00, 0x9C, 0xa1, 0x9d]
    uart_id: desk_uart
    send_every: 1ms
    on_turn_on:
      - delay: 6000ms
      - switch.turn_off: ${device_name}_switch_anti_kollision
    entity_category: "config"

  - platform: uart
    name: "${friendly_name} Child Lock"
    id: switch_child_lock
    icon: mdi:account-lock
    data: [0x9b, 0x06, 0x02, 0x20, 0x00, 0xac, 0xb8, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    on_turn_on:
      - delay: 5000ms
      - switch.turn_off: switch_child_lock
    entity_category: "config"
    
  - platform: uart
    name: "${friendly_name} 1 + 2" # Not available for all control panels // Could be used as wake up?
    id: ${device_name}_switch_1_2
    icon: mdi:counter
    data: [0x9b, 0x06, 0x02, 0x0c, 0x01, 0xac, 0x65, 0x9d]
    uart_id: desk_uart
    entity_category: "config"
    send_every: 1ms
    on_turn_on:
      - delay: 5000ms
      - switch.turn_off: ${device_name}_switch_1_2
    
  - platform: uart
    name: "${friendly_name} M + sitting" # While holding it shows some numbers / M+sitting
    id: ${device_name}_switch_m_sitting
    icon: mdi:script
    data: [0x9b, 0x06, 0x02, 0x20, 0x01, 0x6c, 0x79, 0x9d]
    uart_id: desk_uart
    send_every: 1ms
    entity_category: "config"
    on_turn_on:
      - delay: 15500ms
      - switch.turn_off: ${device_name}_switch_m_sitting

button:
  - platform: template
    name: "${friendly_name} Preset 1"
    id: ${device_name}_button_present1
    icon: mdi:numeric-1-box
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x04, 0x00, 0xac, 0xa3, 0x9d] 

  - platform: template
    name: "${friendly_name} Preset 2"
    id: ${device_name}_button_present2
    icon: mdi:numeric-2-box
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x08, 0x00, 0xac, 0xa6, 0x9d]

  - platform: template
    name: "${friendly_name} Sit" # Preset 3 on some control panels
    id: ${device_name}_button_sit
    icon: mdi:chair-rolling
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x00, 0x01, 0xac, 0x60, 0x9d]

  - platform: template
    name: "${friendly_name} Stand"
    id: ${device_name}_button_stand
    icon: mdi:human-handsup
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x10, 0x00, 0xac, 0xac, 0x9d]

  - platform: template
    name: "${friendly_name} Memory"
    id: ${device_name}_button_m
    icon: mdi:alpha-m-box
    entity_category: "config"
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x20, 0x00, 0xac, 0xb8, 0x9d]

  - platform: template
    name: "${friendly_name} Wake Screen"
    id: ${device_name}_button_wake_screen
    icon: mdi:gesture-tap-button
    entity_category: "config"
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x00, 0x00, 0x6c, 0xa1, 0x9d]

  - platform: template
    name: "${friendly_name} Alarm"
    id: ${device_name}_button_alarm
    icon: mdi:alarm
    on_press:
      - uart.write:
          id: desk_uart
          data: [0x9b, 0x06, 0x02, 0x40, 0x00, 0xAC, 0x90, 0x9d]
  
cover:
  - platform: template
    # icon: mdi:table-chair
    icon: mdi:human-male-height-variant
    id: "${device_name}_desk_cover"
    name: "${friendly_name} Desk"
    device_class: blind
    has_position: true
    position_action:
      - if:
          condition:
            - lambda: !lambda |-
                return pos > id(${device_name}_desk_cover).position;
          then:
            - cover.open: ${device_name}_desk_cover
            - wait_until:
                lambda: |-
                  return id(${device_name}_desk_cover).position  >= pos;
            - cover.stop: ${device_name}_desk_cover
          else:
            - cover.close: ${device_name}_desk_cover
            - wait_until:
                lambda: |-
                  return id(${device_name}_desk_cover).position <= pos;
            - cover.stop: ${device_name}_desk_cover
    stop_action:
      - switch.turn_off: ${device_name}_switch_up
      - switch.turn_off: ${device_name}_switch_down
    open_action:
      - switch.turn_off: ${device_name}_switch_down
      - switch.turn_on: ${device_name}_switch_up
    close_action:
      - switch.turn_off: ${device_name}_switch_up
      - switch.turn_on: ${device_name}_switch_down
    optimistic: false

number:
  - platform: template
    name: "${friendly_name} Desk Height"
    id: ${device_name}_set_desk_height
    min_value: ${min_height}
    max_value: ${max_height}
    icon: "mdi:counter"
    unit_of_measurement: "cm"
    device_class: "distance"
    step: 0.1
    lambda: !lambda |-
      return id(${device_name}_desk_height).state;
    set_action:
      - if:
          condition:
            - lambda: !lambda |-
                return x > id(${device_name}_desk_height).state;
          then:
            - cover.open: ${device_name}_desk_cover
            - wait_until:
                lambda: |-
                  return id(${device_name}_desk_height).state  >= x;
            - cover.stop: ${device_name}_desk_cover
          else:
            - cover.close: ${device_name}_desk_cover
            - wait_until:
                lambda: |-
                  return id(${device_name}_desk_height).state <= x;
            - cover.stop: ${device_name}_desk_cover

```

**Comment by iMicknl** [comment]
Thanks @gitviola, great find! Would you be able to add this to the repo via a pull request? The white-blue cable, do you know if this maps to RJ45 PIN 5?

**Comment by ProZsolt** [comment]
> I figured it out pairing with Claude code the other week. Basically, the controller is programmed in a way that it only sends the hight back to the device that initiated the command. So if you change the hight using the keypad, it will only send the hight updates back to the keypad.

For me the keypad still updates the hight if I change the hight with the ESP, so there should a way to get the hight without tapping to the other cable.

**Comment by globus243** [comment]
You can achieve this by having your ESP constantly send "Wake Up" frames to the Flexispot Controller. I added this to my config:

```yaml
interval:
  - interval: 500ms
    then:
      - if:
          condition:
            and:
              - switch.is_off: switch_up
              - switch.is_off: switch_down
          then:
            - uart.write:
                id: desk_uart
                data: [0x9b, 0x06, 0x02, 0x00, 0x00, 0x6c, 0xa1, 0x9d]
```

You can then also remove everything referencing the button_wake_screen ID.

I am not sure if this has any long-term side effects. Technically the controller is now constantly talking to the ESP, but so far I haven't found any disadvantages to this solution.
