### ISSUE TITLE
Wemos ESP32 S2 mini cannot boot with UART connected

### ISSUE THREAD

**Issue by DrBlokmeister** [iMicknl/LoctekMotion_IoT#77]
This issue might be related to https://github.com/iMicknl/LoctekMotion_IoT/issues/62.

I find that in order to boot my ESP32S2 mini, I have to first connect the +5V and GND pins (also connecting pin20), and then make the UART connection. If not, the device gets into an error mode and does not boot. I do this by tilting the board and inserting only one side into my PCB (connecting 5V, GND, PIN 20), wait a few seconds, then plug in the other side, connecting UART.

If I connect all at once, the status LED blinks slowly and the device does not come online.

I'm using ESPHome and Home Assistant. 

I have an HS11A-A controller. There are two RJ45 ports on my controller, and I use one for the display, and the other one for the ESP. My pin config is as follows. Disregard the cable columns, they refer to internal UTP wiring (cable is checked for crosstalk and good connection).

  | CABLE | CABLE | BOARD
-- | -- | -- | --
Name | DESK | ESP | ESP
RES | 1 |   |  
SWIM | 2 |   |  
unknown | 3 |   |  
PIN 20 | 4 | 1 | GPIO33
RX | 5 | 6 | GPIO9
TX | 6 | 4 | GPIO7
GND | 7 | 3 | GND
+5V | 8 | 5 | Vbus

My UART YAML and virtual screen config is:
```YAML
uart:
  - id: desk_uart
    baud_rate: 9600
    tx_pin: GPIO7 #Desk RJ45 pin 6, ESP RJ45 pin 4
    rx_pin: GPIO9 #Desk RJ45 pin 5, ESP RJ45 pin 6

switch:
  - platform: gpio
    name: "Virtual Screen"
    pin:
      number: GPIO33 #Desk RJ45 pin 4, ESP RJ45 pin 1
      mode: OUTPUT
    restore_mode: ALWAYS_ON
    internal: true
```

Also, I measured the voltage on the UART pins without anything connected. I see 4.7V DC accross the GND and both UART pins. I don't know if this is normal.

Are there things I need to look at?
