### ISSUE TITLE
Wakeup Issues with Esphome

### ISSUE THREAD

**Issue by Algram** [iMicknl/LoctekMotion_IoT#9]
Hi there,

I've successfully integrated my flexispot desk to Home Assistant using your project. Thanks for that!

One problem I am having is, that I need to trigger the wakeup switch (and wait like 5 seconds) before I can send presets events.
Is there any way that this could be more integrated? Ideally I would like to just trigger the preset and the desk to always react.

Thanks!

**Comment by iMicknl** [comment]
Great to hear! Which desk do you own?

Perhaps you could execute the wake up switch on `switch.turn_on`, however I am not sure if this will be the right order. https://esphome.io/components/switch/index.html#switch-turn-on-action

**Comment by Algram** [comment]
@iMicknl  I am using the Flexispot E07 with the HS01B-1 control panel.

I thought about sending the wakeup event before the actual event, but there seems to be a big delay between the wakeup event and the other switches working. I also have to press the wakeup button multiple tims which seems weird.

**Comment by N1c093** [comment]
@Algram Do you shut down your complete desk and ESP everyday?

I do so and implement this workaround for me, which seems to work fine. I send the button "M" to my table after the ESP is booted. After this the ESP can control the table all over the time.

I'm using "Flexispot EK2" with "HS13A-1" Control Panel and "CB38M2B(IB)-1" Control Box


```yaml


esphome:
  name: ${name}
  comment: ${device_name}
  platform: ESP8266 # TODO Change to your platform
  board: nodemcuv2 # TODO Change to your board
  includes:
    - desk_height_sensor.h
  on_boot:
    priority: -10
    then:
      - switch.turn_on: switch_m

```

Maybe this will also resolve your issue?
